### ISSUE TITLE
OSINT on single person challenge (multiple parts)

### ISSUE THREAD

**Issue by Sheepiroo** [jellyctf/challenges#2]
Still planning

Things to find/Flag ideas?
- Firstname Lastname
- Address
- Locations
- IP address
- Posted photos/documents
- Emails
- Organisation - school, work, communities
- Pet name

Sources of information/Ideas
- Reddit
- Github (personal information/credentials in commit)
- Twitter (find twitter alt based on likes/follows, infer personal info from tweets/likes)
- Youtube
- Twitch
- Discord (server message history, documents)
- LinkedIn (School, Work, career history)
- Google drive (Photo metadata - location, date, phone model)
- Instagram

Challenge 1: Photo --> Google Lens (Easy Geolocation)

Challenge 2: Photo --> Slightly harder
- Use name of festival to narrow down location

Challenge 3: Photo --> Tail number + Date Time --> Destination city
Description: This challenge does NOT need any paid accounts. Free options are available to find the required data.
- Photo from reddit Changi airport (source airport)
- https://www.flightera.net/en/planes/9V-OJJ
- Hide datetime image in Exif data OR file name according to phone file format
Flag format jellyCTF{DestinationCity}

Could be home location

Challenge 4: Twitter - birthday from posts/RTs?

Challenge 5: Git repository related?
Real name?

Challenge 6: Leetcode account?

**Comment by arepi-nemui** [comment]
maybe combine the git thing with a site that exposes a .git directory and can be mirrored with https://github.com/kost/dvcs-ripper ?
also contrast boost photo of white paper turned over on desk

**Comment by Sheepiroo** [comment]
Planning board: https://drive.google.com/file/d/1ruFG_ujlb0pB2lA4ql-uft3_ep65eSTl/view?usp=sharing
